<!-- footer -->
<footer class="footer">
  <div class="row">
		<div class="col-xs-4 col-sm-4" style="1px solid black">
		<p><small>&copy; IEEE Student Branch at Louisiana State University 2014</small></p>
    <nav>
      <ul class="list-inline">
        <li><a href="/about">About</a></li>
        <li><a href="/contact">Contact</a></li>
        <li><a href="#">Back to top</a></li>
      </ul>
    </nav>
		</div>
    
		</div class="col-sm-4 col-xs-6">Blarg;</div>
		<div class="col-sm-4 col-xs-6">Snarf;</div>
	</div>
</footer>
