<!-- footer -->
<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="span4" style="1px solid black">
                <nav>
                    <ul class="list-inline">
                        <li><small>&copy; 2014 IEEE Student Branch at Louisiana State University.</small></li>
                        <li><a href="/about">About</a></li>
                        <li><a href="/contact">Contact</a></li>
                        <li><a href="#">Back to top</a></li>
                    </ul>
                </nav>
            </div>
      </div>
      <div class="row">
        <div class="span4">
          <address>
            <Strong>IEEE Student Branch</strong><br>
            Division of Electrical & Computer Engineering<br>
            School of Electrical and Computer Science<br>
            3101 P. F. Taylor Hall<br>
            Louisiana State University<br>
            Baton Rouge, LA 70803, USA<br>
            <abbr title="Email">E:</abbr> <a href="mailto:ieee.lsu@gmail.com">ieee.lsu@gmail.com</a><br>
            <abbr title="Phone">P:</abbr> <a href="tel:+1 225 578 5241">+1 (225) 578-5241</a><br> 
            <abbr title="Fax">F:</abbr> <a href="tel:+1 225 578 5200">+1 (225) 578-5200</a><br>
          </address>
        </div>
    </div>
  </div>
</footer>
