<footer>
          <div class="footer">
            <div class="contact">
              <p>
                ieee.lsu@gmail.com
              </p>
            </div>
            <div class="contact">
                <p>
                    <a href="http://www.ece.lsu.edu">ECE</a> The LSU Department of Electrical and Computer Engineering <br/>
                </p>
            </div>
          </div>
        </div>

				<nav>
					<a class="extra" href="/">home</a>
				</nav>
</footer>
